remote_theme: mmistakes/minimal-mistakes

url    : "https://jaczad.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog

title      : Jacek Zadrożny
subtitle: Ekspert do spraw dostępności
email      : Jacekzadrozny@dostepnik.com.pl
description: "Dostępność to moja pasja i chcę Cię nią zarazić. Pomogę Ci sprawić, by Twoja strona była dostępna dla wszystkich użytkowników. Zapraszam do współpracy."
# author     : Jacek Zadrożny
logo: /assets/img/logo.png

locale: "pl" # See available languages in _data/ui-text.yml

# Site settings
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: false
breadcrumbs: true

# Social media and author info
author:
  name: "Jacek Zadrożny"
  bio: "Ekspert dostępności cyfrowej"
  location: "Polska"
  email: "Jacekzadrozny@dostepnik.com.pl"
  avatar: assets/img/jz-profilowe.png
  links:
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin"
        url: "https://www.linkedin.com/in/jaczad"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/jaczad"
      - label: "Hugging Face"
        icon: "fas fa-fw fa-face-smile"
        url: "https://huggingface.co/jaczad" 
# Footer settings
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:Jacekzadrozny@dostepnik.com.pl"

# Reading settings
show_excerpts: true
excerpt_length: 150

analytics:
  google: #Google Analytics tracking code here

markdown: kramdown

# Pagination settings
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Navigation
include:
  - _data

# Site navigation
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
